"use client";

import { Fragment, type CSSProperties, useEffect, useMemo, useState } from "react";
import { artwork, count, LABEL, LIFE, NAV, pad, PRICE, seedWall, short, type LaneFilter, type LiveSpot, type Spot } from "@/lib/wall";

const Eye=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg>;
const Bookmark=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M6 3h12v18l-6-4-6 4z"/></svg>;
const Search=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>;
const Bolt=()=> <svg viewBox="0 0 24 24" fill="currentColor"><path d="M13 2 3 14h7l-1 8 11-13h-7z"/></svg>;
const colors={music:"#ff7bc3",podcasts:"#6e1f48",games:"#d8ff45",art:"#3b4712",writers:"#151412",letters:"#ece0c2"};

function useColumns(){const[c,set]=useState(5);useEffect(()=>{const u=()=>set(innerWidth<430?3:innerWidth<640?4:5);u();addEventListener("resize",u);return()=>removeEventListener("resize",u)},[]);return c}

function Tile({spot,now,selected,onOpen}:{spot:Spot;now:number;selected:boolean;onOpen:(spot:Spot)=>void}){
 if(spot.vacant)return <div className="spot vacant" id={`s-${pad(spot.no)}`}><div className="stand"><button className="book vbook"><span>Open spot</span></button></div><div className="cap"><strong className="vno">No. {pad(spot.no)}</strong><span className="v2">Claim for {PRICE}</span></div></div>;
 const left=Math.max(0,spot.start+LIFE-now);return <div className={`spot${selected?" open":""}`} id={`s-${pad(spot.no)}`} style={{"--c1":colors[spot.lane]} as CSSProperties}><div className="stand"><button className="book" aria-expanded={selected} onClick={()=>onOpen(spot)}><span className="bk-art" dangerouslySetInnerHTML={{__html:artwork(spot.seed,spot.palette)}}/><span className="bk-strip"><b>{spot.name}</b><small>{LABEL[spot.lane]}</small></span><span className="bk-no">{pad(spot.no)}</span><i className="prog" style={{width:`${left/LIFE*100}%`}}/></button></div><div className="cap" onClick={()=>onOpen(spot)}><span className="cap-l"><span className="t">{short(left)} left</span><span className="meta"><i><Eye/><b>{count(spot.opens)}</b></i><i><Bookmark/><b>{count(spot.saves)}</b></i></span></span></div></div>
}

function Detail({spot,now,onNext}:{spot:LiveSpot;now:number;onNext:()=>void}){return <div className="cover" style={{"--c1":colors[spot.lane]} as CSSProperties}><div className="art" dangerouslySetInnerHTML={{__html:artwork(spot.seed,spot.palette)}}/><div className="body"><div className="issue"><strong>No. {pad(spot.no)}</strong><span>{LABEL[spot.lane]}</span><span className="live">{short(spot.start+LIFE-now)} left</span></div><h2 className="title">{spot.name}</h2><p className="snip">{spot.snippet}</p><div className="links"><a href="#">Visit their page<span>fivehundrd.example/{spot.no}</span></a></div><div className="acts"><button className="act solid">Share</button><button className="act">Save</button><button className="act" onClick={onNext}>Next spot</button></div></div></div>}

export function WallApp({fixture}:{fixture:boolean}){
 const columns=useColumns(),[now]=useState(()=>fixture?new Date("2026-09-24T12:00:00Z").valueOf():Date.now()),wall=useMemo(()=>seedWall(now),[now]);
 const[lane,setLane]=useState<LaneFilter>("all"),[query,setQuery]=useState(""),[selected,setSelected]=useState<number|null>(null),[phone,setPhone]=useState(false);
 useEffect(()=>{const u=()=>setPhone(innerWidth<700);u();addEventListener("resize",u);return()=>removeEventListener("resize",u)},[]);
 useEffect(()=>{document.body.dataset.wallReady="true";return()=>{delete document.body.dataset.wallReady}},[]);
 const visible=wall.filter(s=>(lane==="all"||(!s.vacant&&s.lane===lane))&&(!query||(!s.vacant&&`${s.name} ${s.snippet}`.toLowerCase().includes(query.toLowerCase()))));
 const rows=Array.from({length:Math.ceil(visible.length/columns)},(_,i)=>visible.slice(i*columns,(i+1)*columns)),active=wall.find((s):s is LiveSpot=>!s.vacant&&s.no===selected)??null,live=wall.filter(s=>!s.vacant).length;
 const open=(s:Spot)=>{if(!s.vacant)setSelected(n=>n===s.no?null:s.no)},next=()=>{const list=visible.filter((s):s is LiveSpot=>!s.vacant),i=list.findIndex(s=>s.no===selected);setSelected(list[(i+1)%list.length]?.no??null)};
 return <><header className="top"><div className="site-wrap"><div className="site"><button className="brand" id="brand" onClick={()=>setLane("all")}><span className="bn">Fivehundrd<span className="bdot">.</span></span><span className="slogan">Discover before the crowd.</span></button><nav className="primary">{NAV.map(([k,v])=><a href="#" key={k} className={lane===k?"is-active":""} onClick={e=>{e.preventDefault();setLane(k);setSelected(null)}}>{v}</a>)}</nav><label className="searchbox"><Search/><input type="search" aria-label="Search the wall" placeholder="Search for people, topics, or vibes…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="header-actions"><button className="btn-create"><Bolt/>Create</button><div className="who"><div className="avatar-fallback"/></div></div></div></div></header><div className="stage"><aside className="colophon"><div className="lc"><div className="lc-top"><span>Fivehundrd card</span><span>Today</span></div><h2 className="lc-h">Your wall today<span className="bdot">.</span></h2><div className="lc-stamps"><div><b>0</b><span>opened today</span></div><div><b>0</b><span>saved</span></div><div><b>{live}</b><span>still unseen</span></div></div></div></aside><main><h1 className="sr">The wall</h1><ol className="rack">{rows.length?rows.map((row,i)=><Fragment key={i}><li className="shelf-row"><div className="books" style={{"--cols":columns} as CSSProperties}>{row.map(s=><Tile key={s.no} spot={s} now={now} selected={s.no===selected} onOpen={open}/>)}</div></li>{!phone&&active&&row.some(s=>s.no===active.no)&&<li className="panel"><Detail spot={active} now={now} onNext={next}/></li>}</Fragment>):<li className="no-hits">Nothing on the wall matches <b>{query}</b>.</li>}</ol></main></div>{active&&phone&&<><div className="dveil on" onClick={()=>setSelected(null)}/><div className="dsheet" style={{transform:"none"}} role="dialog" aria-modal="true"><button className="dclose" aria-label="Close" onClick={()=>setSelected(null)}>×</button><div className="dsheet-scroll"><Detail spot={active} now={now} onNext={next}/></div></div></>}<nav className="tabbar"><button className="on">Wall</button><button><Bookmark/>My card</button><button className="tb-create"><Bolt/>Create</button></nav></>
}
